/**
 * hooks/useTask.ts
 *
 * This hook runs the core loop of the app: show a task, collect input,
 * submit it, then immediately show the next task.
 *
 * It handles both kinds of tasks:
 *   - Contribute: save a new word to the device, sync it, load the next prompt.
 *   - Review: send a verdict to the server, load the next entry to review.
 *
 * The Task screen itself is kept simple — it just renders whatever state
 * this hook provides and calls the functions it exposes.
 *
 * Offline behaviour: if there's no internet, contribute tasks are still
 * served from the locally cached concept list. Review tasks require a
 * live server connection (audio URLs can't be generated offline).
 */

import { useState, useCallback } from 'react';
import { useAppStore } from '@/store/app';
import { fetchNextTask, submitReview, skipConcept } from '@/lib/api';
import { queueEntry, getStorageInfo, getRandomCachedConcept, seedTotalContributionCount, updateStreak, getTotalEntryCount } from '@/lib/db/operations';
import { isOnline, syncQueue } from '@/lib/sync/engine';
import type {
  NextTask,
  ReviewSubmission,
  SpeakerMetadata,
} from '@/types';

// ── Types ──────────────────────────────────────────────────────────────────────

const MILESTONES = [1, 10, 50, 100, 500, 1000];

interface UseTaskState {
  task: NextTask | null;      // The current task to show, or null while loading
  isLoading: boolean;
  error: string | null;
  isSubmitting: boolean;
  milestone: number | null;   // Set when the user just crossed a milestone
}

interface UseTaskActions {
  /** Clears the milestone so the celebration stops showing. */
  clearMilestone: () => void;
  /** Saves a new word to the device, uploads it, and loads the next task. */
  submitContribution: (params: {
    nativeWord: string;
    audioBlob?: Blob;
    audioDurationSec?: number;
    speakerMetadata: SpeakerMetadata;
  }) => Promise<void>;

  /** Sends a review verdict to the server and loads the next task. */
  submitVerdict: (submission: ReviewSubmission) => Promise<void>;

  /** Loads the first task. Call this when the Task screen opens. */
  refreshTask: () => Promise<void>;

  /** Logs that the contributor doesn't know this word and loads the next task. */
  skipTask: () => Promise<void>;
}

// ── Hook ───────────────────────────────────────────────────────────────────────

/** Manages task state and submission logic for the Task screen. */
export function useTask(): UseTaskState & UseTaskActions {
  const contributor            = useAppStore(s => s.contributor);
  const incrementContributions = useAppStore(s => s.incrementContributions);
  const setTotalContributions  = useAppStore(s => s.setTotalContributions);
  const setStorageInfo         = useAppStore(s => s.setStorageInfo);
  const setStreakCount         = useAppStore(s => s.setStreakCount);

  const [task, setTask]               = useState<NextTask | null>(null);
  const [isLoading, setIsLoading]     = useState(false);
  const [error, setError]             = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [milestone, setMilestone]     = useState<number | null>(null);

  const clearMilestone = useCallback(() => setMilestone(null), []);

  // ── Fetch next task ─────────────────────────────────────────────────────────

  /**
   * Asks the server what task to show next, or falls back to a cached concept offline.
   * Also updates the local contribution count from the server's authoritative total.
   */
  const fetchTask = useCallback(async () => {
    if (!contributor) return;

    setIsLoading(true);
    setError(null);

    try {
      if (isOnline()) {
        const nextTask = await fetchNextTask(contributor.id);
        setTask(nextTask);

        // The server tells us the real contribution count. Update the local
        // counter in case it drifted (e.g. entries were synced on another device
        // or the persistent counter wasn't set yet).
        if (nextTask.serverContributionCount !== undefined) {
          await seedTotalContributionCount(nextTask.serverContributionCount);
          setTotalContributions(nextTask.serverContributionCount);
        }
      } else {
        // Offline: pick a random concept from the device cache.
        // We can only serve contribute tasks offline because review tasks
        // need a signed audio URL that can only be generated by the server.
        const concept = await getRandomCachedConcept();

        if (concept) {
          setTask({
            taskType: 'contribute',
            prompt: {
              promptId:     `offline-${concept.id}-${Date.now()}`,
              conceptId:    concept.id,
              englishGloss: concept.englishGloss,
              promptType:   concept.promptContext ? 'context'
                          : concept.imagePath     ? 'image'
                          :                        'word',
              contextText: concept.promptContext ?? undefined,
              // No imageUrl — temporary image links can't be generated offline.
            },
          });
        } else {
          setError(
            'No concepts available offline. ' +
            'Connect to the internet to download prompts.'
          );
        }
      }
    } catch (err) {
      const message = err instanceof Error
        ? err.message
        : 'Failed to load the next task. Please try again.';
      setError(message);
    } finally {
      setIsLoading(false);
    }
  }, [contributor]);

  // ── Submit contribution ─────────────────────────────────────────────────────

  /**
   * Handles a new word submission:
   * 1. Saves to the device immediately (offline-safe).
   * 2. Uploads to the server so the server's entry count is up to date.
   * 3. Loads the next task.
   *
   * Uploading before fetching the next task matters: the server uses the
   * entry count to decide whether to serve review tasks (Phase 2 starts
   * at 10 contributions). Without syncing first, the server would always
   * think this person is in Phase 1.
   */
  const submitContribution = useCallback(async (params: {
    nativeWord: string;
    audioBlob?: Blob;
    audioDurationSec?: number;
    speakerMetadata: SpeakerMetadata;
  }) => {
    if (!contributor || task?.taskType !== 'contribute') return;

    setIsSubmitting(true);

    try {
      // Save to device first — this never fails even if the internet is out.
      await queueEntry({
        conceptId:        task.prompt.conceptId,
        englishGloss:     task.prompt.englishGloss,
        nativeWord:       params.nativeWord,
        promptId:         task.prompt.promptId,
        speakerMetadata:  params.speakerMetadata,
        audioBlob:        params.audioBlob,
        audioDurationSec: params.audioDurationSec,
      });

      incrementContributions();

      // Update streak and check for milestones.
      const [newStreak, newTotal] = await Promise.all([updateStreak(), getTotalEntryCount()]);
      setStreakCount(newStreak);

      const seen: number[] = JSON.parse(localStorage.getItem('thok_milestones_seen') ?? '[]');
      const crossed = MILESTONES.find(m => newTotal >= m && !seen.includes(m));
      if (crossed !== undefined) {
        seen.push(crossed);
        localStorage.setItem('thok_milestones_seen', JSON.stringify(seen));
        setMilestone(crossed);
      }

      // Upload to the server before asking for the next task.
      // If the upload fails, the entry stays on the device and retries later.
      if (isOnline()) {
        await syncQueue(contributor.id).catch(() => {
          // Non-fatal — entry is safe on the device and will be retried.
        });
      }

      // Update the storage gauge since we just added an audio file.
      const storage = await getStorageInfo();
      setStorageInfo(storage);

      // Show the next task without any confirmation screen.
      await fetchTask();
    } catch (err) {
      const message = err instanceof Error
        ? err.message
        : 'Failed to save your contribution. Please try again.';
      setError(message);
    } finally {
      setIsSubmitting(false);
    }
  }, [contributor, task, incrementContributions, setStorageInfo, fetchTask]);

  // ── Skip task ───────────────────────────────────────────────────────────────

  /**
   * Logs that the contributor doesn't know this word, then loads the next task.
   *
   * The server call is fire-and-forget — we don't wait for it before moving on.
   * If it fails, the skip simply isn't recorded, which is acceptable.
   * The skip does not count toward the contribution total.
   */
  const skipTask = useCallback(async () => {
    if (!contributor || task?.taskType !== 'contribute') return;

    // Log the skip without blocking the UI — best effort.
    skipConcept(contributor.id, task.prompt.conceptId).catch(() => {});

    await fetchTask();
  }, [contributor, task, fetchTask]);

  // ── Submit verdict ──────────────────────────────────────────────────────────

  /**
   * Sends the reviewer's verdict to the server and immediately loads the next entry.
   */
  const submitVerdict = useCallback(async (submission: ReviewSubmission) => {
    if (!contributor || task?.taskType !== 'review') return;

    setIsSubmitting(true);

    try {
      await submitReview(contributor.id, submission);

      // Update streak — reviewing counts the same as contributing toward daily activity.
      const newStreak = await updateStreak();
      setStreakCount(newStreak);

      await fetchTask();
    } catch (err) {
      const message = err instanceof Error
        ? err.message
        : 'Failed to submit your verdict. Please try again.';
      setError(message);
    } finally {
      setIsSubmitting(false);
    }
  }, [contributor, task, fetchTask]);

  return {
    task,
    isLoading,
    error,
    isSubmitting,
    milestone,
    clearMilestone,
    submitContribution,
    submitVerdict,
    skipTask,
    refreshTask: fetchTask,
  };
}
