-- =============================================================================
-- Seed ~300 basic sentences for Dinka language collection
--
-- Covers 20 communicative categories drawn from standard language-learning
-- frameworks and Dinka cultural context. Each sentence is tagged with an
-- intent so researchers can filter by communicative goal.
--
-- Sentences with [name] or [place] are templates — contributors say any name
-- or place they like when recording, and the prompt_context explains this.
-- =============================================================================

INSERT INTO concepts (id, english_gloss, concept_type, swadesh_list, intent, prompt_context) VALUES

-- ── Greetings ────────────────────────────────────────────────────────────────
('s_0001', 'How are you?',           'sentence', FALSE, 'greeting',  NULL),
('s_0002', 'I am fine.',             'sentence', FALSE, 'greeting',  NULL),
('s_0003', 'Good morning.',          'sentence', FALSE, 'greeting',  NULL),
('s_0004', 'Good evening.',          'sentence', FALSE, 'greeting',  NULL),
('s_0005', 'How did you sleep?',     'sentence', FALSE, 'greeting',  NULL),
('s_0006', 'Welcome.',               'sentence', FALSE, 'greeting',  NULL),
('s_0007', 'See you tomorrow.',      'sentence', FALSE, 'farewell',  NULL),
('s_0008', 'Have a safe journey.',   'sentence', FALSE, 'farewell',  NULL),
('s_0009', 'Take care.',             'sentence', FALSE, 'farewell',  NULL),
('s_0010', 'Peace be with you.',     'sentence', FALSE, 'greeting',  NULL),
('s_0011', 'Enjoy your day.',        'sentence', FALSE, 'farewell',  NULL),
('s_0012', 'Come back soon.',        'sentence', FALSE, 'farewell',  NULL),

-- ── Introductions ────────────────────────────────────────────────────────────
('s_0013', 'What is your name?',     'sentence', FALSE, 'question',      NULL),
('s_0014', 'My name is [name].',     'sentence', FALSE, 'introduction',  'Say this sentence using any name — your own or someone else''s.'),
('s_0015', 'Where are you from?',    'sentence', FALSE, 'question',      NULL),
('s_0016', 'I am from [place].',     'sentence', FALSE, 'introduction',  'Say this sentence using any place — a town, state, or region.'),
('s_0017', 'Where do you live?',     'sentence', FALSE, 'question',      NULL),
('s_0018', 'How many children do you have?', 'sentence', FALSE, 'question', NULL),
('s_0019', 'I have three children.', 'sentence', FALSE, 'introduction',  NULL),
('s_0020', 'We live together.',      'sentence', FALSE, 'introduction',  NULL),
('s_0021', 'My family is here.',     'sentence', FALSE, 'introduction',  NULL),
('s_0022', 'Where is your family?',  'sentence', FALSE, 'question',      NULL),
('s_0023', 'I speak a little Dinka.','sentence', FALSE, 'introduction',  NULL),

-- ── Family ───────────────────────────────────────────────────────────────────
('s_0024', 'This is my mother.',     'sentence', FALSE, 'introduction',  NULL),
('s_0025', 'This is my father.',     'sentence', FALSE, 'introduction',  NULL),
('s_0026', 'This is my brother.',    'sentence', FALSE, 'introduction',  NULL),
('s_0027', 'This is my sister.',     'sentence', FALSE, 'introduction',  NULL),
('s_0028', 'My father is working.',  'sentence', FALSE, 'description',   NULL),
('s_0029', 'My mother is cooking.',  'sentence', FALSE, 'description',   NULL),
('s_0030', 'My brother is sleeping.','sentence', FALSE, 'description',   NULL),
('s_0031', 'My sister is at school.','sentence', FALSE, 'description',   NULL),
('s_0032', 'The baby is sleeping.',  'sentence', FALSE, 'description',   NULL),
('s_0033', 'The child is crying.',   'sentence', FALSE, 'description',   NULL),
('s_0034', 'The children are playing.','sentence',FALSE, 'description',  NULL),

-- ── Basic needs ──────────────────────────────────────────────────────────────
('s_0035', 'I want water.',          'sentence', FALSE, 'basic_need',    NULL),
('s_0036', 'I am hungry.',           'sentence', FALSE, 'basic_need',    NULL),
('s_0037', 'I am thirsty.',          'sentence', FALSE, 'basic_need',    NULL),
('s_0038', 'I am tired.',            'sentence', FALSE, 'basic_need',    NULL),
('s_0039', 'I am sick.',             'sentence', FALSE, 'basic_need',    NULL),
('s_0040', 'I need help.',           'sentence', FALSE, 'basic_need',    NULL),
('s_0041', 'I want to eat.',         'sentence', FALSE, 'basic_need',    NULL),
('s_0042', 'I want to sleep.',       'sentence', FALSE, 'basic_need',    NULL),
('s_0043', 'I want more water.',     'sentence', FALSE, 'basic_need',    NULL),
('s_0044', 'I am full.',             'sentence', FALSE, 'basic_need',    NULL),
('s_0045', 'I need medicine.',       'sentence', FALSE, 'basic_need',    NULL),
('s_0046', 'Is there water here?',   'sentence', FALSE, 'question',      NULL),
('s_0047', 'There is no water.',     'sentence', FALSE, 'description',   NULL),
('s_0048', 'I need to go.',          'sentence', FALSE, 'basic_need',    NULL),
('s_0049', 'I need to rest.',        'sentence', FALSE, 'basic_need',    NULL),

-- ── Understanding & communication ────────────────────────────────────────────
('s_0050', 'I don''t understand.',   'sentence', FALSE, 'understanding', NULL),
('s_0051', 'Please say that again.', 'sentence', FALSE, 'request',       NULL),
('s_0052', 'Please speak slowly.',   'sentence', FALSE, 'request',       NULL),
('s_0053', 'Do you speak English?',  'sentence', FALSE, 'question',      NULL),
('s_0054', 'What does this mean?',   'sentence', FALSE, 'question',      NULL),
('s_0055', 'How do you say this in Dinka?', 'sentence', FALSE, 'question', NULL),
('s_0056', 'I don''t know.',         'sentence', FALSE, 'answer',        NULL),
('s_0057', 'I think so.',            'sentence', FALSE, 'answer',        NULL),
('s_0058', 'Can you repeat that?',   'sentence', FALSE, 'request',       NULL),

-- ── Questions ────────────────────────────────────────────────────────────────
('s_0059', 'What is this called?',   'sentence', FALSE, 'question',      NULL),
('s_0060', 'Where is the market?',   'sentence', FALSE, 'question',      NULL),
('s_0061', 'Where is the hospital?', 'sentence', FALSE, 'question',      NULL),
('s_0062', 'Where is the bathroom?', 'sentence', FALSE, 'question',      NULL),
('s_0063', 'How far is it?',         'sentence', FALSE, 'question',      NULL),
('s_0064', 'How much does it cost?', 'sentence', FALSE, 'question',      NULL),
('s_0065', 'Where are you?',         'sentence', FALSE, 'question',      NULL),
('s_0066', 'Who is that?',           'sentence', FALSE, 'question',      NULL),
('s_0067', 'What happened?',         'sentence', FALSE, 'question',      NULL),
('s_0068', 'What are you doing?',    'sentence', FALSE, 'question',      NULL),
('s_0069', 'What do you need?',      'sentence', FALSE, 'question',      NULL),
('s_0070', 'When will you come?',    'sentence', FALSE, 'question',      NULL),
('s_0071', 'Where are you going?',   'sentence', FALSE, 'question',      NULL),
('s_0072', 'Is everything okay?',    'sentence', FALSE, 'question',      NULL),
('s_0073', 'Which one?',             'sentence', FALSE, 'question',      NULL),
('s_0074', 'How many?',              'sentence', FALSE, 'question',      NULL),
('s_0075', 'Why are you here?',      'sentence', FALSE, 'question',      NULL),
('s_0076', 'What did you say?',      'sentence', FALSE, 'question',      NULL),
('s_0077', 'Where is the clinic?',   'sentence', FALSE, 'question',      NULL),
('s_0078', 'Where is the key?',      'sentence', FALSE, 'question',      NULL),

-- ── Directions ───────────────────────────────────────────────────────────────
('s_0079', 'Turn left.',             'sentence', FALSE, 'direction',     NULL),
('s_0080', 'Turn right.',            'sentence', FALSE, 'direction',     NULL),
('s_0081', 'Go straight.',           'sentence', FALSE, 'direction',     NULL),
('s_0082', 'Stop here.',             'sentence', FALSE, 'direction',     NULL),
('s_0083', 'It is near.',            'sentence', FALSE, 'location',      NULL),
('s_0084', 'It is far.',             'sentence', FALSE, 'location',      NULL),
('s_0085', 'It is here.',            'sentence', FALSE, 'location',      NULL),
('s_0086', 'It is there.',           'sentence', FALSE, 'location',      NULL),
('s_0087', 'We are almost there.',   'sentence', FALSE, 'location',      NULL),
('s_0088', 'It is inside.',          'sentence', FALSE, 'location',      NULL),
('s_0089', 'It is outside.',         'sentence', FALSE, 'location',      NULL),
('s_0090', 'It is behind you.',      'sentence', FALSE, 'location',      NULL),
('s_0091', 'It is in front.',        'sentence', FALSE, 'location',      NULL),
('s_0092', 'It is on the table.',    'sentence', FALSE, 'location',      NULL),
('s_0093', 'It is under the chair.', 'sentence', FALSE, 'location',      NULL),

-- ── Buying & selling ─────────────────────────────────────────────────────────
('s_0094', 'How much?',              'sentence', FALSE, 'transaction',   NULL),
('s_0095', 'That is too expensive.', 'sentence', FALSE, 'transaction',   NULL),
('s_0096', 'I want to buy this.',    'sentence', FALSE, 'transaction',   NULL),
('s_0097', 'I want to sell this.',   'sentence', FALSE, 'transaction',   NULL),
('s_0098', 'Do you have more?',      'sentence', FALSE, 'transaction',   NULL),
('s_0099', 'I have no money.',       'sentence', FALSE, 'transaction',   NULL),
('s_0100', 'I need change.',         'sentence', FALSE, 'transaction',   NULL),
('s_0101', 'That price is fair.',    'sentence', FALSE, 'transaction',   NULL),
('s_0102', 'This is enough.',        'sentence', FALSE, 'transaction',   NULL),
('s_0103', 'Give me a smaller one.', 'sentence', FALSE, 'transaction',   NULL),

-- ── Feelings & states ────────────────────────────────────────────────────────
('s_0104', 'I am happy.',            'sentence', FALSE, 'feeling',       NULL),
('s_0105', 'I am sad.',              'sentence', FALSE, 'feeling',       NULL),
('s_0106', 'I am afraid.',           'sentence', FALSE, 'feeling',       NULL),
('s_0107', 'I am angry.',            'sentence', FALSE, 'feeling',       NULL),
('s_0108', 'I am not well.',         'sentence', FALSE, 'feeling',       NULL),
('s_0109', 'I feel better.',         'sentence', FALSE, 'feeling',       NULL),
('s_0110', 'I feel weak.',           'sentence', FALSE, 'feeling',       NULL),
('s_0111', 'I am confused.',         'sentence', FALSE, 'feeling',       NULL),
('s_0112', 'I am late.',             'sentence', FALSE, 'description',   NULL),
('s_0113', 'Today is busy.',         'sentence', FALSE, 'description',   NULL),
('s_0114', 'I am worried.',          'sentence', FALSE, 'feeling',       NULL),

-- ── Time ─────────────────────────────────────────────────────────────────────
('s_0115', 'What time is it?',       'sentence', FALSE, 'question',      NULL),
('s_0116', 'I will come tomorrow.',  'sentence', FALSE, 'scheduling',    NULL),
('s_0117', 'Come now.',              'sentence', FALSE, 'command',       NULL),
('s_0118', 'Wait a moment.',         'sentence', FALSE, 'command',       NULL),
('s_0119', 'Not yet.',               'sentence', FALSE, 'answer',        NULL),
('s_0120', 'Already.',               'sentence', FALSE, 'answer',        NULL),
('s_0121', 'Later.',                 'sentence', FALSE, 'answer',        NULL),
('s_0122', 'Right now.',             'sentence', FALSE, 'answer',        NULL),
('s_0123', 'I am coming.',           'sentence', FALSE, 'answer',        NULL),

-- ── Emergency ────────────────────────────────────────────────────────────────
('s_0124', 'Help!',                  'sentence', FALSE, 'emergency',     NULL),
('s_0125', 'Call a doctor.',         'sentence', FALSE, 'emergency',     NULL),
('s_0126', 'Call the police.',       'sentence', FALSE, 'emergency',     NULL),
('s_0127', 'I am in pain.',          'sentence', FALSE, 'emergency',     NULL),
('s_0128', 'I am lost.',             'sentence', FALSE, 'emergency',     NULL),
('s_0129', 'I need a doctor.',       'sentence', FALSE, 'emergency',     NULL),
('s_0130', 'Where does it hurt?',    'sentence', FALSE, 'question',      NULL),

-- ── Commands & instructions ───────────────────────────────────────────────────
('s_0131', 'Come here.',             'sentence', FALSE, 'command',       NULL),
('s_0132', 'Sit down.',              'sentence', FALSE, 'command',       NULL),
('s_0133', 'Stand up.',              'sentence', FALSE, 'command',       NULL),
('s_0134', 'Go there.',              'sentence', FALSE, 'command',       NULL),
('s_0135', 'Wait for me.',           'sentence', FALSE, 'command',       NULL),
('s_0136', 'Come with me.',          'sentence', FALSE, 'command',       NULL),
('s_0137', 'Follow me.',             'sentence', FALSE, 'command',       NULL),
('s_0138', 'Bring it.',              'sentence', FALSE, 'command',       NULL),
('s_0139', 'Take it.',               'sentence', FALSE, 'command',       NULL),
('s_0140', 'Give it to me.',         'sentence', FALSE, 'command',       NULL),
('s_0141', 'Put it down.',           'sentence', FALSE, 'command',       NULL),
('s_0142', 'Open it.',               'sentence', FALSE, 'command',       NULL),
('s_0143', 'Close it.',              'sentence', FALSE, 'command',       NULL),
('s_0144', 'Be careful.',            'sentence', FALSE, 'command',       NULL),
('s_0145', 'Don''t run.',            'sentence', FALSE, 'command',       NULL),
('s_0146', 'Listen carefully.',      'sentence', FALSE, 'command',       NULL),
('s_0147', 'Go to school.',          'sentence', FALSE, 'command',       NULL),
('s_0148', 'Do your homework.',      'sentence', FALSE, 'command',       NULL),
('s_0149', 'Eat your food.',         'sentence', FALSE, 'command',       NULL),
('s_0150', 'Drink your water.',      'sentence', FALSE, 'command',       NULL),
('s_0151', 'Wash your hands.',       'sentence', FALSE, 'command',       NULL),
('s_0152', 'Repeat after me.',       'sentence', FALSE, 'command',       NULL),
('s_0153', 'Open the window.',       'sentence', FALSE, 'command',       NULL),
('s_0154', 'Close the door.',        'sentence', FALSE, 'command',       NULL),

-- ── Politeness ───────────────────────────────────────────────────────────────
('s_0155', 'You are welcome.',       'sentence', FALSE, 'politeness',    NULL),
('s_0156', 'Excuse me.',             'sentence', FALSE, 'politeness',    NULL),
('s_0157', 'It is okay.',            'sentence', FALSE, 'politeness',    NULL),
('s_0158', 'No problem.',            'sentence', FALSE, 'politeness',    NULL),
('s_0159', 'I am sorry.',            'sentence', FALSE, 'politeness',    NULL),
('s_0160', 'That is right.',         'sentence', FALSE, 'confirmation',  NULL),
('s_0161', 'That is wrong.',         'sentence', FALSE, 'confirmation',  NULL),
('s_0162', 'Thank you for coming.',  'sentence', FALSE, 'politeness',    NULL),
('s_0163', 'Please check my hand.',  'sentence', FALSE, 'request',       NULL),
('s_0164', 'Please open the door.',  'sentence', FALSE, 'request',       NULL),
('s_0165', 'Please tell me.',        'sentence', FALSE, 'request',       NULL),
('s_0166', 'Please teach me.',       'sentence', FALSE, 'request',       NULL),

-- ── Health & body ─────────────────────────────────────────────────────────────
('s_0167', 'My head hurts.',         'sentence', FALSE, 'health',        NULL),
('s_0168', 'My stomach hurts.',      'sentence', FALSE, 'health',        NULL),
('s_0169', 'My leg hurts.',          'sentence', FALSE, 'health',        NULL),
('s_0170', 'My back hurts.',         'sentence', FALSE, 'health',        NULL),
('s_0171', 'I have a fever.',        'sentence', FALSE, 'health',        NULL),
('s_0172', 'I have a cough.',        'sentence', FALSE, 'health',        NULL),
('s_0173', 'I feel sick.',           'sentence', FALSE, 'health',        NULL),
('s_0174', 'The child is sick.',     'sentence', FALSE, 'health',        NULL),
('s_0175', 'The cow is sick.',       'sentence', FALSE, 'health',        NULL),

-- ── Food & eating ────────────────────────────────────────────────────────────
('s_0176', 'I want some food.',      'sentence', FALSE, 'food',          NULL),
('s_0177', 'I want rice.',           'sentence', FALSE, 'food',          NULL),
('s_0178', 'I want fish.',           'sentence', FALSE, 'food',          NULL),
('s_0179', 'I want meat.',           'sentence', FALSE, 'food',          NULL),
('s_0180', 'I want vegetables.',     'sentence', FALSE, 'food',          NULL),
('s_0181', 'I want tea.',            'sentence', FALSE, 'food',          NULL),
('s_0182', 'This food is good.',     'sentence', FALSE, 'description',   NULL),
('s_0183', 'This food is hot.',      'sentence', FALSE, 'description',   NULL),
('s_0184', 'This food is cold.',     'sentence', FALSE, 'description',   NULL),
('s_0185', 'We are eating now.',     'sentence', FALSE, 'routine',       NULL),

-- ── Weather & environment ─────────────────────────────────────────────────────
('s_0186', 'It is raining.',         'sentence', FALSE, 'weather',       NULL),
('s_0187', 'It is very hot.',        'sentence', FALSE, 'weather',       NULL),
('s_0188', 'It is very cold.',       'sentence', FALSE, 'weather',       NULL),
('s_0189', 'The wind is strong.',    'sentence', FALSE, 'weather',       NULL),
('s_0190', 'The sun is bright.',     'sentence', FALSE, 'weather',       NULL),
('s_0191', 'It is cloudy.',          'sentence', FALSE, 'weather',       NULL),
('s_0192', 'The river is high.',     'sentence', FALSE, 'weather',       NULL),
('s_0193', 'The river is flooded.',  'sentence', FALSE, 'weather',       NULL),
('s_0194', 'The road is muddy.',     'sentence', FALSE, 'description',   NULL),
('s_0195', 'It is a beautiful day.', 'sentence', FALSE, 'weather',       NULL),
('s_0196', 'It is dry today.',       'sentence', FALSE, 'weather',       NULL),
('s_0197', 'It is windy.',           'sentence', FALSE, 'weather',       NULL),

-- ── School & learning ────────────────────────────────────────────────────────
('s_0198', 'I am studying.',         'sentence', FALSE, 'education',     NULL),
('s_0199', 'I am reading.',          'sentence', FALSE, 'routine',       NULL),
('s_0200', 'I am writing.',          'sentence', FALSE, 'routine',       NULL),
('s_0201', 'I am learning Dinka.',   'sentence', FALSE, 'education',     NULL),
('s_0202', 'I have a question.',     'sentence', FALSE, 'education',     NULL),
('s_0203', 'I know the answer.',     'sentence', FALSE, 'education',     NULL),
('s_0204', 'We have class today.',   'sentence', FALSE, 'education',     NULL),

-- ── Work & daily life ─────────────────────────────────────────────────────────
('s_0205', 'I am working.',          'sentence', FALSE, 'work',          NULL),
('s_0206', 'I am going to work.',    'sentence', FALSE, 'work',          NULL),
('s_0207', 'I am going home.',       'sentence', FALSE, 'travel',        NULL),
('s_0208', 'I am going to the farm.','sentence', FALSE, 'work',          NULL),
('s_0209', 'I am carrying water.',   'sentence', FALSE, 'work',          NULL),
('s_0210', 'I am washing clothes.',  'sentence', FALSE, 'work',          NULL),
('s_0211', 'I am cooking dinner.',   'sentence', FALSE, 'work',          NULL),
('s_0212', 'We are working together.','sentence',FALSE, 'work',          NULL),
('s_0213', 'We finished today.',     'sentence', FALSE, 'work',          NULL),
('s_0214', 'Let us start early.',    'sentence', FALSE, 'work',          NULL),
('s_0215', 'I am resting.',          'sentence', FALSE, 'routine',       NULL),

-- ── Religion & community ─────────────────────────────────────────────────────
('s_0216', 'We are praying.',        'sentence', FALSE, 'community',     NULL),
('s_0217', 'The ceremony starts soon.','sentence',FALSE,'community',     NULL),
('s_0218', 'Many people are here.',  'sentence', FALSE, 'community',     NULL),
('s_0219', 'We are singing.',        'sentence', FALSE, 'community',     NULL),
('s_0220', 'We are meeting today.',  'sentence', FALSE, 'community',     NULL),
('s_0221', 'Everyone is welcome.',   'sentence', FALSE, 'community',     NULL),
('s_0222', 'Let us pray together.',  'sentence', FALSE, 'community',     NULL),
('s_0223', 'The meeting is finished.','sentence',FALSE, 'community',     NULL),
('s_0224', 'We are going to church.','sentence', FALSE, 'community',     NULL),
('s_0225', 'The community is helping.','sentence',FALSE,'community',     NULL),

-- ── Farming ──────────────────────────────────────────────────────────────────
('s_0226', 'We are planting.',       'sentence', FALSE, 'farming',       NULL),
('s_0227', 'We are harvesting.',     'sentence', FALSE, 'farming',       NULL),
('s_0228', 'The field is ready.',    'sentence', FALSE, 'farming',       NULL),
('s_0229', 'It needs rain.',         'sentence', FALSE, 'farming',       NULL),
('s_0230', 'The crops are growing.', 'sentence', FALSE, 'farming',       NULL),
('s_0231', 'The ground is dry.',     'sentence', FALSE, 'farming',       NULL),
('s_0232', 'The harvest is good.',   'sentence', FALSE, 'farming',       NULL),
('s_0233', 'The seeds are ready.',   'sentence', FALSE, 'farming',       NULL),
('s_0234', 'Bring the tools.',       'sentence', FALSE, 'farming',       NULL),

-- ── Cattle & livestock ───────────────────────────────────────────────────────
('s_0235', 'Where are the cattle?',  'sentence', FALSE, 'livestock',     NULL),
('s_0236', 'The cows are here.',     'sentence', FALSE, 'livestock',     NULL),
('s_0237', 'The cows are eating.',   'sentence', FALSE, 'livestock',     NULL),
('s_0238', 'The cows need water.',   'sentence', FALSE, 'livestock',     NULL),
('s_0239', 'Bring the cattle.',      'sentence', FALSE, 'livestock',     NULL),
('s_0240', 'Count the cattle.',      'sentence', FALSE, 'livestock',     NULL),
('s_0241', 'The calf is small.',     'sentence', FALSE, 'livestock',     NULL),
('s_0242', 'The goats are outside.', 'sentence', FALSE, 'livestock',     NULL),
('s_0243', 'The sheep are nearby.',  'sentence', FALSE, 'livestock',     NULL),
('s_0244', 'We are herding cattle.', 'sentence', FALSE, 'livestock',     NULL),
('s_0245', 'The cattle are safe.',   'sentence', FALSE, 'livestock',     NULL),

-- ── Village life ─────────────────────────────────────────────────────────────
('s_0246', 'The village is quiet.',  'sentence', FALSE, 'community',     NULL),
('s_0247', 'Everyone is here.',      'sentence', FALSE, 'community',     NULL),
('s_0248', 'The bridge is broken.',  'sentence', FALSE, 'description',   NULL),
('s_0249', 'We crossed the river.',  'sentence', FALSE, 'travel',        NULL),
('s_0250', 'We arrived safely.',     'sentence', FALSE, 'travel',        NULL),
('s_0251', 'The market is busy.',    'sentence', FALSE, 'description',   NULL),
('s_0252', 'The path is clear.',     'sentence', FALSE, 'description',   NULL),
('s_0253', 'People are waiting.',    'sentence', FALSE, 'description',   NULL),

-- ── Travel & transport ───────────────────────────────────────────────────────
('s_0254', 'We are leaving now.',    'sentence', FALSE, 'travel',        NULL),
('s_0255', 'The road is closed.',    'sentence', FALSE, 'travel',        NULL),
('s_0256', 'The bus is late.',       'sentence', FALSE, 'travel',        NULL),
('s_0257', 'Let us walk.',           'sentence', FALSE, 'travel',        NULL),
('s_0258', 'We will arrive soon.',   'sentence', FALSE, 'travel',        NULL),
('s_0259', 'I am going to the market.','sentence',FALSE,'travel',        NULL),
('s_0260', 'I arrived safely.',      'sentence', FALSE, 'travel',        NULL),

-- ── Home & household ─────────────────────────────────────────────────────────
('s_0261', 'I am at home.',          'sentence', FALSE, 'location',      NULL),
('s_0262', 'The door is open.',      'sentence', FALSE, 'description',   NULL),
('s_0263', 'The water is finished.', 'sentence', FALSE, 'description',   NULL),
('s_0264', 'My phone is here.',      'sentence', FALSE, 'location',      NULL),
('s_0265', 'Everyone is home.',      'sentence', FALSE, 'description',   NULL),
('s_0266', 'The house is clean.',    'sentence', FALSE, 'description',   NULL),
('s_0267', 'The room is empty.',     'sentence', FALSE, 'description',   NULL),

-- ── Phone & communication ─────────────────────────────────────────────────────
('s_0268', 'Can you hear me?',       'sentence', FALSE, 'communication', NULL),
('s_0269', 'Call me later.',         'sentence', FALSE, 'communication', NULL),
('s_0270', 'I will call tomorrow.',  'sentence', FALSE, 'communication', NULL),
('s_0271', 'My phone is dead.',      'sentence', FALSE, 'communication', NULL),
('s_0272', 'There is no signal.',    'sentence', FALSE, 'communication', NULL),
('s_0273', 'I received your message.','sentence',FALSE, 'communication', NULL),
('s_0274', 'Please answer the phone.','sentence',FALSE, 'request',       NULL),
('s_0275', 'Send me a message.',     'sentence', FALSE, 'request',       NULL),
('s_0276', 'I am speaking now.',     'sentence', FALSE, 'communication', NULL),

-- ── Daily routine ─────────────────────────────────────────────────────────────
('s_0277', 'I woke up.',             'sentence', FALSE, 'routine',       NULL),
('s_0278', 'I ate breakfast.',       'sentence', FALSE, 'routine',       NULL),
('s_0279', 'I went to work.',        'sentence', FALSE, 'routine',       NULL),
('s_0280', 'I came home.',           'sentence', FALSE, 'routine',       NULL),
('s_0281', 'I took a bath.',         'sentence', FALSE, 'routine',       NULL),
('s_0282', 'I am going to sleep.',   'sentence', FALSE, 'routine',       NULL),
('s_0283', 'I cooked dinner.',       'sentence', FALSE, 'routine',       NULL),

-- ── Nature ───────────────────────────────────────────────────────────────────
('s_0284', 'The river is full.',     'sentence', FALSE, 'nature',        NULL),
('s_0285', 'The river is low.',      'sentence', FALSE, 'nature',        NULL),
('s_0286', 'The tree is big.',       'sentence', FALSE, 'description',   NULL),
('s_0287', 'The moon is bright.',    'sentence', FALSE, 'nature',        NULL),
('s_0288', 'The stars are beautiful.','sentence',FALSE, 'nature',        NULL),
('s_0289', 'The sun is rising.',     'sentence', FALSE, 'nature',        NULL),
('s_0290', 'The grass is green.',    'sentence', FALSE, 'nature',        NULL),
('s_0291', 'The fire is hot.',       'sentence', FALSE, 'nature',        NULL),

-- ── Describing people ────────────────────────────────────────────────────────
('s_0292', 'He is tall.',            'sentence', FALSE, 'description',   NULL),
('s_0293', 'She is short.',          'sentence', FALSE, 'description',   NULL),
('s_0294', 'He is strong.',          'sentence', FALSE, 'description',   NULL),
('s_0295', 'She is kind.',           'sentence', FALSE, 'description',   NULL),
('s_0296', 'He is young.',           'sentence', FALSE, 'description',   NULL),
('s_0297', 'She is old.',            'sentence', FALSE, 'description',   NULL),
('s_0298', 'They are happy.',        'sentence', FALSE, 'description',   NULL),
('s_0299', 'He is tired.',           'sentence', FALSE, 'description',   NULL),

-- ── Describing objects ───────────────────────────────────────────────────────
('s_0300', 'It is big.',             'sentence', FALSE, 'description',   NULL),
('s_0301', 'It is small.',           'sentence', FALSE, 'description',   NULL),
('s_0302', 'It is heavy.',           'sentence', FALSE, 'description',   NULL),
('s_0303', 'It is clean.',           'sentence', FALSE, 'description',   NULL),
('s_0304', 'It is dirty.',           'sentence', FALSE, 'description',   NULL),
('s_0305', 'It is new.',             'sentence', FALSE, 'description',   NULL),
('s_0306', 'It is old.',             'sentence', FALSE, 'description',   NULL),
('s_0307', 'It is broken.',          'sentence', FALSE, 'description',   NULL),
('s_0308', 'It works.',              'sentence', FALSE, 'description',   NULL),

-- ── Permission & requests ─────────────────────────────────────────────────────
('s_0309', 'Can I sit here?',        'sentence', FALSE, 'permission',    NULL),
('s_0310', 'Can I come in?',         'sentence', FALSE, 'permission',    NULL),
('s_0311', 'Can I help?',            'sentence', FALSE, 'permission',    NULL),
('s_0312', 'May I ask something?',   'sentence', FALSE, 'permission',    NULL),
('s_0313', 'Can you wait?',          'sentence', FALSE, 'request',       NULL),
('s_0314', 'Can you help me?',       'sentence', FALSE, 'request',       NULL),
('s_0315', 'Can you show me?',       'sentence', FALSE, 'request',       NULL),

-- ── Social ───────────────────────────────────────────────────────────────────
('s_0316', 'Let''s go together.',    'sentence', FALSE, 'social',        NULL),
('s_0317', 'I will visit you.',      'sentence', FALSE, 'social',        NULL),
('s_0318', 'I missed you.',          'sentence', FALSE, 'social',        NULL),
('s_0319', 'Stay a little longer.',  'sentence', FALSE, 'social',        NULL),
('s_0320', 'Welcome to my home.',    'sentence', FALSE, 'social',        NULL),
('s_0321', 'Have a seat.',           'sentence', FALSE, 'social',        NULL),
('s_0322', 'We are friends.',        'sentence', FALSE, 'social',        NULL),

-- ── Daily problems ────────────────────────────────────────────────────────────
('s_0323', 'I lost my phone.',       'sentence', FALSE, 'problem',       NULL),
('s_0324', 'I cannot find it.',      'sentence', FALSE, 'problem',       NULL),
('s_0325', 'I forgot.',              'sentence', FALSE, 'problem',       NULL),
('s_0326', 'The road is blocked.',   'sentence', FALSE, 'problem',       NULL),
('s_0327', 'There is no electricity.','sentence',FALSE, 'problem',       NULL),
('s_0328', 'There is no signal.',    'sentence', FALSE, 'problem',       NULL),

-- ── Numbers & quantities ──────────────────────────────────────────────────────
('s_0329', 'I want one.',            'sentence', FALSE, 'quantity',      NULL),
('s_0330', 'I want two.',            'sentence', FALSE, 'quantity',      NULL),
('s_0331', 'Give me three.',         'sentence', FALSE, 'quantity',      NULL),
('s_0332', 'We have five.',          'sentence', FALSE, 'quantity',      NULL),
('s_0333', 'That is enough.',        'sentence', FALSE, 'quantity',      NULL),
('s_0334', 'I need more.',           'sentence', FALSE, 'quantity',      NULL),
('s_0335', 'Not enough.',            'sentence', FALSE, 'quantity',      NULL),
('s_0336', 'Too many.',              'sentence', FALSE, 'quantity',      NULL)

ON CONFLICT (id) DO NOTHING;
